[providers]
python = {}
node = {}

[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "gunicorn --timeout 120 run:app"
