[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cd frontend && npm install && npm run build"

[deploy]
startCommand = "gunicorn --timeout 120 run:app"
healthCheckPath = "/api/health"
healthCheckTimeout = 100
